Repository lblod/frontend-lpdc, pull requests merged in 2025-04, with the labels that each got.

#21 fix: update woodpecker configuration
  .woodpecker/.push-latest-build.yml
  .woodpecker/.push-tagged-build.yml
  .woodpecker/.test.yml
Labels: internal

#20 feature: Add validation before saving
  app/components/details-page.js
  app/services/public-service.js
Labels: enhancement

#23 fix: show error messages before asking for confirmation to publish product instance
  app/components/details-page.js
Labels: bug
